# Generated by Django 5.2.11 on 2026-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_real_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageconfig",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "网站超级管理员"),
                    ("site_admin", "网站管理员"),
                    ("enterprise_leader", "企业负责人"),
                    ("enterprise_admin", "企业用户管理员"),
                    ("enterprise_user", "企业用户普通账户"),
                    ("temporary", "临时账户"),
                ],
                max_length=20,
                verbose_name="用户类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "网站超级管理员"),
                    ("site_admin", "网站管理员"),
                    ("enterprise_leader", "企业负责人"),
                    ("enterprise_admin", "企业用户管理员"),
                    ("enterprise_user", "企业用户普通账户"),
                    ("temporary", "临时账户"),
                ],
                default="temporary",
                max_length=20,
                verbose_name="用户类型",
            ),
        ),
    ]
