# Generated by Django 5.2.11 on 2026-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_pageconfig_user_type_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否可用"),
        ),
    ]
