# Generated by Django 5.2.11 on 2026-03-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_company_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="用户唯一ID"
            ),
        ),
    ]
