# Generated by Django 4.2.30 on 2026-05-23 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0013_productsku_sale_location_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="客户名称")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="地址")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系人"
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="company.company",
                        verbose_name="所属企业",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "db_table": "customer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="价格"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_price_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="customer.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_price_histories",
                        to="store.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "报价历史",
                "verbose_name_plural": "报价历史",
                "db_table": "customer_price_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configured_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="配置时间"),
                ),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_visibilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="配置人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibilities",
                        to="customer.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "visible_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visible_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="可见用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户可见性",
                "verbose_name_plural": "客户可见性",
                "db_table": "customer_visibility",
                "ordering": ["-configured_at"],
                "unique_together": {("customer", "visible_user")},
            },
        ),
        migrations.CreateModel(
            name="CustomerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="价格"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="customer.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_products",
                        to="store.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户商品",
                "verbose_name_plural": "客户商品",
                "db_table": "customer_product",
                "ordering": ["-created_at"],
                "unique_together": {("customer", "product")},
            },
        ),
    ]
