# Generated by Django 5.2.11 on 2026-03-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="店铺名称")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("taobao", "淘宝"),
                            ("tmall", "天猫"),
                            ("jd", "京东"),
                            ("pdd", "拼多多"),
                            ("douyin", "抖音电商"),
                            ("kuaishou", "快手电商"),
                            ("1688", "1688"),
                            ("xiaohongshu", "小红书"),
                            ("wechat", "微信小店"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="电商平台",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("children_clothing", "童装"),
                            ("crystal_bracelet", "水晶手串"),
                            ("earrings", "耳钉耳饰"),
                            ("necklace", "项链"),
                            ("ring", "戒指"),
                            ("bags", "箱包"),
                            ("shoes", "鞋类"),
                            ("cosmetics", "化妆品"),
                            ("home", "家居用品"),
                            ("food", "食品"),
                            ("electronics", "电子产品"),
                            ("clothing", "服装"),
                            ("accessories", "配饰"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="店铺品类",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="店铺描述"),
                ),
                (
                    "shop_url",
                    models.URLField(blank=True, null=True, verbose_name="店铺链接"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系人姓名"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="联系电话"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="company.company",
                        verbose_name="所属企业",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="店铺管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "db_table": "store",
                "ordering": ["-created_at"],
            },
        ),
    ]
