# Generated by Django 5.2.11 on 2026-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="api_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="API配置"),
        ),
    ]
