# Generated by Django 5.2.11 on 2026-03-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPullTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待拉取"),
                            ("pulling", "拉取中"),
                            ("success", "拉取成功"),
                            ("failed", "拉取失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="拉取开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="拉取结束时间"),
                ),
                ("order_count", models.IntegerField(default=0, verbose_name="拉取订单数")),
                (
                    "new_order_count",
                    models.IntegerField(default=0, verbose_name="新增订单数"),
                ),
                (
                    "updated_order_count",
                    models.IntegerField(default=0, verbose_name="更新订单数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="任务参数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_tasks",
                        to="store.store",
                        verbose_name="所属店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据拉取任务",
                "verbose_name_plural": "数据拉取任务",
                "db_table": "data_pull_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "platform_order_id",
                    models.CharField(max_length=100, verbose_name="平台订单ID"),
                ),
                (
                    "platform_order_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="平台订单号"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("waitbuyerpay", "等待买家付款"),
                            ("waitsellersend", "等待卖家发货"),
                            ("waitbuyerreceive", "等待买家确认收货"),
                            ("success", "交易成功"),
                            ("cancel", "交易关闭"),
                            ("paid_but_not_fund", "已支付，未到账"),
                            ("confirm_goods", "已收货"),
                            ("waitsellerconfirm", "等待卖家确认订单"),
                            ("waitbuyerconfirm", "等待买家确认订单"),
                            ("confirm_goods_but_not_fund", "已收货，未到账"),
                            ("confirm_goods_and_has_subsidy", "已收货，已贴现"),
                            ("send_goods_but_not_fund", "已发货，未到账"),
                            ("waitlogisticstakein", "等待物流揽件"),
                            ("waitbuyersign", "等待买家签收"),
                            ("signinsuccess", "买家已签收"),
                            ("signinfailed", "签收失败"),
                            ("waitselleract", "等待卖家操作"),
                            ("waitbuyerconfirmaction", "等待买家确认操作"),
                            ("waitsellerpush", "等待卖家推进"),
                        ],
                        max_length=50,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("no_refund", "无退款"),
                            ("waitselleragree", "等待卖家同意"),
                            ("refundsuccess", "退款成功"),
                        ],
                        default="no_refund",
                        max_length=30,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "buyer_login_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="买家账号"
                    ),
                ),
                (
                    "buyer_open_uid",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="买家Open UID"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="订单总额"
                    ),
                ),
                (
                    "sum_product_payment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="商品总额"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="运费"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="折扣"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="退款金额"
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="订单创建时间")),
                (
                    "pay_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "modify_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "seller_remark_icon",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="卖家备注图标"
                    ),
                ),
                (
                    "seller_memo",
                    models.TextField(blank=True, null=True, verbose_name="卖家备注"),
                ),
                (
                    "buyer_memo",
                    models.TextField(blank=True, null=True, verbose_name="买家备注"),
                ),
                (
                    "alipay_trade_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="支付宝交易号"
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="交易类型"
                    ),
                ),
                (
                    "flow_template_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="流程模板代码"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="业务类型"
                    ),
                ),
                (
                    "can_send_goods",
                    models.BooleanField(default=True, verbose_name="是否可发货"),
                ),
                (
                    "cant_send_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="不可发货原因"
                    ),
                ),
                (
                    "platform_raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="平台原始数据"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="同步时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="store.store",
                        verbose_name="所属店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "platform_item_id",
                    models.CharField(max_length=100, verbose_name="平台子订单ID"),
                ),
                (
                    "product_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="商品ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=500, verbose_name="商品名称")),
                (
                    "product_img_url",
                    models.TextField(blank=True, null=True, verbose_name="商品图片URL"),
                ),
                (
                    "product_snapshot_url",
                    models.URLField(blank=True, null=True, verbose_name="商品快照URL"),
                ),
                (
                    "product_cargo_number",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="商品货号"
                    ),
                ),
                (
                    "sku_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="SKU ID"
                    ),
                ),
                (
                    "sku_specs",
                    models.JSONField(blank=True, default=list, verbose_name="SKU规格"),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="单价"
                    ),
                ),
                (
                    "item_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="商品金额"
                    ),
                ),
                (
                    "entry_discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="子订单折扣"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单位"
                    ),
                ),
                (
                    "item_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waitbuyerpay", "等待买家付款"),
                            ("waitsellersend", "等待卖家发货"),
                            ("waitbuyerreceive", "等待买家确认收货"),
                            ("success", "交易成功"),
                            ("cancel", "交易关闭"),
                            ("paid_but_not_fund", "已支付，未到账"),
                            ("confirm_goods", "已收货"),
                            ("waitsellerconfirm", "等待卖家确认订单"),
                            ("waitbuyerconfirm", "等待买家确认订单"),
                            ("confirm_goods_but_not_fund", "已收货，未到账"),
                            ("confirm_goods_and_has_subsidy", "已收货，已贴现"),
                            ("send_goods_but_not_fund", "已发货，未到账"),
                            ("waitlogisticstakein", "等待物流揽件"),
                            ("waitbuyersign", "等待买家签收"),
                            ("signinsuccess", "买家已签收"),
                            ("signinfailed", "签收失败"),
                            ("waitselleract", "等待卖家操作"),
                            ("waitbuyerconfirmaction", "等待买家确认操作"),
                            ("waitsellerpush", "等待卖家推进"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="子订单状态",
                    ),
                ),
                (
                    "item_refund_status",
                    models.CharField(
                        choices=[
                            ("no_refund", "无退款"),
                            ("waitselleragree", "等待卖家同意"),
                            ("refundsuccess", "退款成功"),
                        ],
                        default="no_refund",
                        max_length=30,
                        verbose_name="子订单退款状态",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="退款单ID"
                    ),
                ),
                (
                    "guarantees_terms",
                    models.JSONField(blank=True, default=list, verbose_name="保障条款"),
                ),
                (
                    "logistics_status",
                    models.IntegerField(blank=True, null=True, verbose_name="物流状态"),
                ),
                (
                    "gmt_create",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "gmt_modified",
                    models.DateTimeField(blank=True, null=True, verbose_name="修改时间"),
                ),
                (
                    "platform_raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="平台原始数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.order",
                        verbose_name="所属订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单商品",
                "verbose_name_plural": "订单商品",
                "db_table": "order_item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderReceiver",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "receiver_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="收货人姓名"
                    ),
                ),
                (
                    "receiver_phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="收货人电话"
                    ),
                ),
                (
                    "receiver_mobile",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="收货人手机"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="区县"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="详细地址"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="邮编"
                    ),
                ),
                (
                    "to_division_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="收货地址编码"
                    ),
                ),
                (
                    "full_address",
                    models.TextField(blank=True, null=True, verbose_name="完整地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="store.order",
                        verbose_name="所属订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单收货人",
                "verbose_name_plural": "订单收货人",
                "db_table": "order_receiver",
            },
        ),
        migrations.CreateModel(
            name="PlatformApiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="App Key"
                    ),
                ),
                (
                    "app_secret",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="App Secret"
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Access Token"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Refresh Token"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token过期时间"
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_config",
                        to="store.store",
                        verbose_name="关联店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台API配置",
                "verbose_name_plural": "平台API配置",
                "db_table": "platform_api_config",
            },
        ),
        migrations.CreateModel(
            name="StoreData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50, verbose_name="数据类型")),
                ("data_date", models.DateField(verbose_name="数据日期")),
                (
                    "data_value",
                    models.JSONField(blank=True, default=dict, verbose_name="数据值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="store.store",
                        verbose_name="所属店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺数据记录",
                "verbose_name_plural": "店铺数据记录",
                "db_table": "store_data",
                "ordering": ["-data_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreDataConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_pull_enabled",
                    models.BooleanField(default=False, verbose_name="是否自动拉取"),
                ),
                (
                    "pull_interval_hours",
                    models.IntegerField(default=1, verbose_name="拉取间隔(小时)"),
                ),
                (
                    "last_pull_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次拉取时间"),
                ),
                (
                    "next_pull_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次拉取时间"),
                ),
                (
                    "pull_status",
                    models.CharField(
                        choices=[
                            ("pending", "待拉取"),
                            ("pulling", "拉取中"),
                            ("success", "拉取成功"),
                            ("failed", "拉取失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="拉取状态",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_config",
                        to="store.store",
                        verbose_name="关联店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺数据配置",
                "verbose_name_plural": "店铺数据配置",
                "db_table": "store_data_config",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "order_status"], name="order_store_i_ff7250_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["create_time"], name="order_create__939187_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["platform_order_id"], name="order_platfor_3390d3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("store", "platform_order_id")},
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="order_item_order_i_08a5da_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["platform_item_id"], name="order_item_platfor_b8e261_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storedata",
            unique_together={("store", "data_type", "data_date")},
        ),
    ]
