# Generated by Django 5.2.11 on 2026-03-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="货号"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "product_type",
                    models.CharField(
                        choices=[("accessory", "手串配件"), ("finished", "手串成品")],
                        max_length=20,
                        verbose_name="商品类型",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="成本价格"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="售卖价格"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="库位"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="供应商"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="company.company",
                        verbose_name="所属企业",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="材质"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="尺寸"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="颜色"
                    ),
                ),
            ],
            options={
                "verbose_name": "手串配件",
                "verbose_name_plural": "手串配件",
                "db_table": "accessory",
            },
        ),
        migrations.CreateModel(
            name="FinishedProduct",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "beads",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="串珠"
                    ),
                ),
            ],
            options={
                "verbose_name": "手串成品",
                "verbose_name_plural": "手串成品",
                "db_table": "finished_product",
            },
        ),
        migrations.CreateModel(
            name="FinishedProductAccessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "accessory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finished_products",
                        to="store.accessory",
                        verbose_name="配件",
                    ),
                ),
                (
                    "finished_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="store.finishedproduct",
                        verbose_name="所属成品",
                    ),
                ),
            ],
            options={
                "verbose_name": "成品配件组成",
                "verbose_name_plural": "成品配件组成",
                "db_table": "finished_product_accessory",
                "unique_together": {("finished_product", "accessory")},
            },
        ),
    ]
