# Generated by Django 5.2.11 on 2026-03-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_accessory_finishedproduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bead",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="材质"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="尺寸"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="颜色"
                    ),
                ),
            ],
            options={
                "verbose_name": "串珠",
                "verbose_name_plural": "串珠",
                "db_table": "bead",
            },
        ),
        migrations.RemoveField(
            model_name="finishedproduct",
            name="beads",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("bead", "串珠"), ("accessory", "手串配件"), ("finished", "手串成品")],
                max_length=20,
                verbose_name="商品类型",
            ),
        ),
        migrations.CreateModel(
            name="FinishedProductBead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "bead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finished_products",
                        to="store.bead",
                        verbose_name="串珠",
                    ),
                ),
                (
                    "finished_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beads",
                        to="store.finishedproduct",
                        verbose_name="所属成品",
                    ),
                ),
            ],
            options={
                "verbose_name": "成品串珠组成",
                "verbose_name_plural": "成品串珠组成",
                "db_table": "finished_product_bead",
                "unique_together": {("finished_product", "bead")},
            },
        ),
    ]
