# Generated by Django 5.2.11 on 2026-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_bead_remove_finishedproduct_beads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="temp_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
