# Generated by Django 5.2.11 on 2026-03-29 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_temp_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="temp_field",
        ),
    ]
