# Generated by Django 5.2.11 on 2026-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishedproduct",
            name="elastic_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="弹性成本"
            ),
        ),
        migrations.AddField(
            model_name="finishedproduct",
            name="labor_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="工费"
            ),
        ),
    ]
