# Generated by Django 5.2.11 on 2026-05-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_finishedproduct_elastic_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bead",
            name="quality_level",
            field=models.IntegerField(default=5, verbose_name="品质等级(1-10)"),
        ),
        migrations.AddField(
            model_name="bead",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="bead",
            name="weight",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="单颗克重"
            ),
        ),
    ]
