# Generated by Django 5.2.11 on 2026-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_bead_quality_level_bead_remark_bead_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_cost",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=12, verbose_name="采购成本(元/克)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="单颗成本"
            ),
        ),
    ]
