# Generated by Django 5.2.11 on 2026-05-22
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_bead_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="size",
            field=models.IntegerField(blank=True, null=True, verbose_name="规格"),
        ),
    ]
