# Generated by Django 4.2.30 on 2026-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_productsku_sale_location_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bead",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="单颗克重"
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="克重"
            ),
        ),
    ]
