# Generated by Django 4.2.30 on 2026-05-29 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0014_alter_bead_weight_alter_productsku_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("purchase_cost", "采购成本"),
                            ("cost_price", "成本价格"),
                            ("selling_price", "销售价格"),
                        ],
                        max_length=20,
                        verbose_name="价格类型",
                    ),
                ),
                (
                    "old_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="变更前价格"
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="变更后价格"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="store.product",
                        verbose_name="关联商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格变更历史",
                "verbose_name_plural": "价格变更历史",
                "db_table": "price_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
