# Generated by Django 5.2.11 on 2026-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="企业名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="企业编号"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="企业地址"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系人姓名"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="联系电话"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否可用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "企业",
                "verbose_name_plural": "企业",
                "db_table": "company",
            },
        ),
    ]
